spring.application.name=java-advanced-backend-service
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/oauth2/jwks
logging.level.org.springframework.security=DEBUG

# Actuator Configuration
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.endpoint.health.show-components=always

# Prometheus Configuration
management.prometheus.metrics.export.enabled=true
management.metrics.tags.application=product-service